#!/bin/bash

curl https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Charli_XCX_-_Brat_%28album_cover%29.png/1200px-Charli_XCX_-_Brat_%28album_cover%29.png > bratcover.png
aws s3 cp bratcover.png s3://ds2022-azt6gn/
aws s3 presign --expires-in 604800 s3://ds2022-azt6gn/bratcover.png

#https://ds2022-azt6gn.s3.us-east-1.amazonaws.com/bratcover.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWOOXUDZ5RYPC3PNA%2F20240927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240927T163857Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=e7ca1729b37b64281a4498831f085991950a89974fd36d8e51a46460a94e02b8
